"""add email_verified to User

Revision ID: 0ea39e6f35f2
Revises: 7ea3c0c8bb84
Create Date: 2021-10-10 22:49:17.713472

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0ea39e6f35f2"
down_revision = "7ea3c0c8bb84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_verified")
    # ### end Alembic commands ###
