"""Item

Revision ID: 29448dd29b72
Revises: a7b16fc59aa5
Create Date: 2021-09-26 19:47:58.183099

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "29448dd29b72"
down_revision = "a7b16fc59aa5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_superuser")
    # ### end Alembic commands ###
