"""User

Revision ID: 4acd0291b040
Revises: f222e6d3bcf6
Create Date: 2021-09-26 19:24:25.020543

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4acd0291b040"
down_revision = "f222e6d3bcf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_email_key", "user", type_="unique")
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_unique_constraint("user_username_key", "user", ["username"])
    op.create_unique_constraint("user_email_key", "user", ["email"])
    # ### end Alembic commands ###
