"""add created_at to Item

Revision ID: 566a36be1102
Revises: e5937235dc10
Create Date: 2021-10-06 22:16:48.238732

"""
import sqlalchemy as sa
from alembic import op

import src

# revision identifiers, used by Alembic.
revision = "566a36be1102"
down_revision = "e5937235dc10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column("created_at", src.libs.sa.timezone.TZDateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "created_at")
    # ### end Alembic commands ###
