"""update Item

Revision ID: 7ea3c0c8bb84
Revises: 566a36be1102
Create Date: 2021-10-07 19:28:05.927312

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ea3c0c8bb84"
down_revision = "566a36be1102"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item", "title", existing_type=sa.VARCHAR(length=40), nullable=False
    )
    op.alter_column("item", "owner_id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("item", "owner_id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column("item", "title", existing_type=sa.VARCHAR(length=40), nullable=True)
    # ### end Alembic commands ###
