"""add item

Revision ID: e5937235dc10
Revises: 29448dd29b72
Create Date: 2021-10-06 22:13:16.628463

"""


# revision identifiers, used by Alembic.
revision = "e5937235dc10"
down_revision = "29448dd29b72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
